/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { DigitalReserveContract } from "./DigitalReserve";
import { ERC20Contract } from "./ERC20";
import { IDigitalReserveContract } from "./IDigitalReserve";
import { IERC20Contract } from "./IERC20";
import { ILendingPoolContract } from "./ILendingPool";
import { ILendingPoolAddressesProviderContract } from "./ILendingPoolAddressesProvider";
import { IProtocolDataProviderContract } from "./IProtocolDataProvider";
import { IUniswapV2FactoryContract } from "./IUniswapV2Factory";
import { IUniswapV2PairContract } from "./IUniswapV2Pair";
import { IUniswapV2Router01Contract } from "./IUniswapV2Router01";
import { IUniswapV2Router02Contract } from "./IUniswapV2Router02";
import { MigrationsContract } from "./Migrations";
import { OwnableContract } from "./Ownable";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "DigitalReserve"): DigitalReserveContract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "IDigitalReserve"): IDigitalReserveContract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "ILendingPool"): ILendingPoolContract;
      require(
        name: "ILendingPoolAddressesProvider"
      ): ILendingPoolAddressesProviderContract;
      require(name: "IProtocolDataProvider"): IProtocolDataProviderContract;
      require(name: "IUniswapV2Factory"): IUniswapV2FactoryContract;
      require(name: "IUniswapV2Pair"): IUniswapV2PairContract;
      require(name: "IUniswapV2Router01"): IUniswapV2Router01Contract;
      require(name: "IUniswapV2Router02"): IUniswapV2Router02Contract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Ownable"): OwnableContract;
    }
  }
}

export {
  DigitalReserveContract,
  DigitalReserveInstance,
} from "./DigitalReserve";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export {
  IDigitalReserveContract,
  IDigitalReserveInstance,
} from "./IDigitalReserve";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export { ILendingPoolContract, ILendingPoolInstance } from "./ILendingPool";
export {
  ILendingPoolAddressesProviderContract,
  ILendingPoolAddressesProviderInstance,
} from "./ILendingPoolAddressesProvider";
export {
  IProtocolDataProviderContract,
  IProtocolDataProviderInstance,
} from "./IProtocolDataProvider";
export {
  IUniswapV2FactoryContract,
  IUniswapV2FactoryInstance,
} from "./IUniswapV2Factory";
export {
  IUniswapV2PairContract,
  IUniswapV2PairInstance,
} from "./IUniswapV2Pair";
export {
  IUniswapV2Router01Contract,
  IUniswapV2Router01Instance,
} from "./IUniswapV2Router01";
export {
  IUniswapV2Router02Contract,
  IUniswapV2Router02Instance,
} from "./IUniswapV2Router02";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { OwnableContract, OwnableInstance } from "./Ownable";
