/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IProtocolDataProviderContract
  extends Truffle.Contract<IProtocolDataProviderInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<IProtocolDataProviderInstance>;
}

type AllEvents = never;

export interface IProtocolDataProviderInstance
  extends Truffle.ContractInstance {
  ADDRESSES_PROVIDER(txDetails?: Truffle.TransactionDetails): Promise<string>;

  getAllReservesTokens(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ symbol: string; tokenAddress: string }[]>;

  getAllATokens(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ symbol: string; tokenAddress: string }[]>;

  getReserveConfigurationData(
    asset: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: BN;
    1: BN;
    2: BN;
    3: BN;
    4: BN;
    5: boolean;
    6: boolean;
    7: boolean;
    8: boolean;
    9: boolean;
  }>;

  getReserveData(
    asset: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: BN;
    1: BN;
    2: BN;
    3: BN;
    4: BN;
    5: BN;
    6: BN;
    7: BN;
    8: BN;
    9: BN;
  }>;

  getUserReserveData(
    asset: string,
    user: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: BN;
    1: BN;
    2: BN;
    3: BN;
    4: BN;
    5: BN;
    6: BN;
    7: BN;
    8: boolean;
  }>;

  getReserveTokensAddresses(
    asset: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: string; 1: string; 2: string }>;

  methods: {
    ADDRESSES_PROVIDER(txDetails?: Truffle.TransactionDetails): Promise<string>;

    getAllReservesTokens(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ symbol: string; tokenAddress: string }[]>;

    getAllATokens(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ symbol: string; tokenAddress: string }[]>;

    getReserveConfigurationData(
      asset: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: BN;
      1: BN;
      2: BN;
      3: BN;
      4: BN;
      5: boolean;
      6: boolean;
      7: boolean;
      8: boolean;
      9: boolean;
    }>;

    getReserveData(
      asset: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: BN;
      1: BN;
      2: BN;
      3: BN;
      4: BN;
      5: BN;
      6: BN;
      7: BN;
      8: BN;
      9: BN;
    }>;

    getUserReserveData(
      asset: string,
      user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: BN;
      1: BN;
      2: BN;
      3: BN;
      4: BN;
      5: BN;
      6: BN;
      7: BN;
      8: boolean;
    }>;

    getReserveTokensAddresses(
      asset: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: string; 1: string; 2: string }>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
